# Introducción al uso de numpy

En primer logar para usar numpy es necesario importarla, para ello usar el siguiente comando,
`import numpy as np`

## Cración de vectores
En primer lugar veamos como crear un vector en Numpy de una dimensión

In [1]:
import numpy as np

V1D = np.array([1, 2, 3]) #Creación de un vector de 1D
print (V1D) #Pintar el vector
print(V1D.shape) #Tamaño del vector
print(V1D[1]) #Acceder a un elemento del vector

[1 2 3]
(3,)
2


A continuación crearemos un vector de dos dimensiones o una matriz

In [2]:
V2D = np.array([[1,2,3],[4,5,6]]) #Creación de un vector de 2D
print (V2D) #Pintar el vector
print(V2D.shape) #Tamaño del vector
print(V2D[0, 1]) #Acceder a un elemento del vector  

[[1 2 3]
 [4 5 6]]
(2, 3)
2


## Funciones para creación
Numpy ofrece diversas funciones para crear Array multidimensional, entre las que cabe destacar:
- **Vector de zeros**: se crea un vector con ceros en todas sus posiciones `np.zeros((filas,columnas))`
- **Vector de unos**: se crea un vector con unos en todas sus posiciones `np.ones((filas,columnas))`
- **Vector con una constante**: se crea un vector con una constante en todas sus posiciones `np.full((filas,columnas), constante)`
- **Identidad**: creación de una matriz identidad `np.eye(tamaño)`
- **Aleatorio**: creación de un vector con elementos aleatorios `np.random.random(filas, columnas)`

Esta son solo algunas de las operaciones, se pueden realizar muchas más que puedes ver en la documentación de numpy

In [3]:
#Ceros
ceros = np.zeros((3,2))
print(ceros)

#Unos
unos = np.ones((3,3))    
print(unos)              

#Contante
const = np.full((3,3), 10)  
print(const)    
                     
#Identidad
identidad = np.eye(4)        
print(identidad)              
                     
#Aleatorio
aleatorio = np.random.random((5,10))  
print(aleatorio)                     

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.41845648 0.40647661 0.48805853 0.56384593 0.31842519 0.55099764
  0.48416428 0.50369421 0.31398026 0.56966602]
 [0.15221197 0.35612668 0.66617418 0.5428179  0.75084135 0.76628791
  0.54809788 0.68776493 0.93911162 0.33152057]
 [0.39526244 0.31399045 0.26181188 0.28114634 0.74283739 0.01844223
  0.59074327 0.49411828 0.40307135 0.38713273]
 [0.07692341 0.68194901 0.13526766 0.40788278 0.02102993 0.76543139
  0.34208774 0.05473228 0.93044347 0.51999817]
 [0.46759369 0.13461635 0.47042423 0.30071068 0.09008235 0.46847606
  0.99313043 0.93905815 0.69627313 0.83595337]]


# Operaciones matemáticas
Numpy también ofrece la opción de realizar operaciones matemáticas sobre operaciones. Algunas de estas operaciones son:
- **Suma**: realiza la suma de dos vectores,  se puede usar tanto el operador '+' como la función `np.add(x, y`
- **Resta**: realiza la resta de dos vectores, se puede usar tanto el operador '-' como la función `np.subtract(x, y`
- **Multiplicación**: realiza la multiplicación de cada elemento **OJO!! NO el producto matricial**, se puede usar tanto el operador '*' como la función `np.multiply(x, y)`
- **División**: realiza la división de cada elemento, se puede calcular tanto con el operador '/' como con la función `np.divide(x, y)`
- **Producto matricial**: la realización del producto matricial se ppuede realizar con la función `np.dot(x, y)`
- **Suma de los elementos**: se puede hacer la suma de los elementos de una matriz con la operacion `np.sum(x)`

In [4]:
A = np.array([[1 , 2], [3, 4]])
B = np.ones((2,2))

#Suma
print(A+B)
print(np.add(A, B))

[[2. 3.]
 [4. 5.]]
[[2. 3.]
 [4. 5.]]


In [5]:
#Resta
print(A-B)
print(np.subtract(A,B))

[[0. 1.]
 [2. 3.]]
[[0. 1.]
 [2. 3.]]


In [6]:
#Multiplicación 
print(A*B)
print(np.multiply(A, B))

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [7]:
#División
print(A/B)
print(np.divide(A,B))

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [8]:
#Producto Matricial
print(np.dot(A,B))

[[3. 3.]
 [7. 7.]]


In [9]:
#Suma de los elementos de la matriz
print(np.sum(A))

10
